### ISSUE TITLE
Some functionality does not work

### ISSUE THREAD

**Issue by shadiaali** [webdevmatics/chatter#1]
I followed the installation instructions closely, installing on Laravel 6 after installing vue auth. When navigating the /forums page, the view is unstyled/uncompiled and some functionality (such as delete and reply to thread) does not work. Bootstrap scaffolding is installed and compiled. I think the issue may be to do with the directory/tree but I'm not sure. Could you do a fresh install following your instructions and try to replicate the issue? I would really like to use this package as it's the most updated/complete version of Chatter but I simply cannot get it working. There are no errors in the console. 
![Screen Shot 2020-04-01 at 7 32 13 AM](https://user-images.githubusercontent.com/23483037/78132636-18df0800-73eb-11ea-8355-c5261e7e22a0.png)

**Comment by shadiaali** [comment]
Update: I have also tried on Laravel 5.8, same result.  I have noticed the following:
1. @yield('css')/@yield('js') is missing in the master layout file/app.blade.php (in `resources/views/layouts/app.blade.php`) 
2. All of the src link css/js urls point to `/vendor/devdojo` resources (eg, in `vendor/webdevmatics/chatter/src/Views/home.blade.php`, the url: `<link href="{{ url('/vendor/devdojo/chatter/assets/vendor/spectrum/spectrum.css') }}" rel="stylesheet">`) Should this be pointing at vendor/webdevmatics instead?

**Comment by webdevmatics** [comment]
Updated readme file please refer to installation section you need to do extra step number 7 to get it working.
